version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
    # environment:
    #   - POSTGRES_PASSWORD=postgres_password
  redis: 
    image: 'redis:latest'
  server: 
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app

